import { NextRequest, NextResponse } from 'next/server'

const API_KEY = process.env.TWELVEDATA_API_KEY!
const BASE_URL = 'https://api.twelvedata.com'

function toApiSymbol(pair: string): string {
  return pair.slice(0, 3) + '/' + pair.slice(3)
}

function pipMultiplier(pair: string): number {
  return pair.toUpperCase().includes('JPY') ? 100 : 10000
}

interface Candle {
  datetime: string
  open: number
  high: number
  low: number
  close: number
}

async function fetchCandles(symbol: string, interval: string, count: number): Promise<Candle[]> {
  const url = `${BASE_URL}/time_series?symbol=${symbol}&interval=${interval}&outputsize=${count}&apikey=${API_KEY}&format=JSON`
  const res = await fetch(url, { next: { revalidate: 60 } })
  const data = await res.json()
  if (data.status === 'error' || !data.values) throw new Error(data.message ?? `Geen data voor ${symbol} ${interval}`)
  return data.values.map((v: Record<string, string>) => ({
    datetime: v.datetime,
    open: parseFloat(v.open),
    high: parseFloat(v.high),
    low: parseFloat(v.low),
    close: parseFloat(v.close),
  }))
}

function calcEMA(candles: Candle[], period: number): number {
  const closes = [...candles].reverse().map(c => c.close)
  const multiplier = 2 / (period + 1)
  let ema = closes[0]
  for (let i = 1; i < closes.length; i++) {
    ema = closes[i] * multiplier + ema * (1 - multiplier)
  }
  return ema
}

function calcDonchian(candles: Candle[], period: number) {
  const recent = candles.slice(0, period)
  const upper = Math.max(...recent.map(c => c.high))
  const lower = Math.min(...recent.map(c => c.low))
  return { upper, lower, middle: (upper + lower) / 2 }
}

export interface CriterionResult {
  key: string
  label: string
  pass: boolean
  weight: number
  value: string
  reason: string
  autoGenerated?: boolean
}

export interface AnalysisResult {
  score: number
  recommendation: 'WEL_DOEN' | 'NIET_DOEN' | 'TWIJFEL'
  criteria: CriterionResult[]
  snapshot: Record<string, number | boolean>
  error?: string
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const {
      pair,
      direction,
      entryPrice,
      fomoThreshold = 10,
      criteria: userCriteria = [],
      threshold = 60,
    } = body

    const symbol = toApiSymbol(pair)
    const pipMul = pipMultiplier(pair)

    // Fetch 5min, 1H, 4H candles in parallel
    const [candles5m, candles1h, candles4h] = await Promise.all([
      fetchCandles(symbol, '5min', 50),
      fetchCandles(symbol, '1h', 30),
      fetchCandles(symbol, '4h', 25),
    ])

    // Indicators
    const ema11_5m  = calcEMA(candles5m, 11)
    const ema25_5m  = calcEMA(candles5m, 25)
    const ema11_1h  = calcEMA(candles1h, 11)
    const ema25_1h  = calcEMA(candles1h, 25)
    const ema11_4h  = calcEMA(candles4h, 11)
    const ema25_4h  = calcEMA(candles4h, 25)
    const donchian  = calcDonchian(candles5m, 9)

    const lastCandle   = candles5m[0]
    const prevCandle   = candles5m[1]
    const recentMovePips = Math.abs(lastCandle.close - prevCandle.close) * pipMul
    const emaDiffPips    = Math.abs(ema11_5m - ema25_5m) * pipMul
    const channelWidthPips = (donchian.upper - donchian.lower) * pipMul
    const positionInChannel = channelWidthPips > 0
      ? ((lastCandle.close - donchian.lower) / (donchian.upper - donchian.lower)) * 100
      : 50

    const isLong = direction === 'LONG'

    // ── 1H en 4H zijn de zwaarste criteria ──────────────────────────────────
    const defaultCriteria: CriterionResult[] = [
      {
        key: 'ema_trend_1h',
        label: 'Trend 1-uurs grafiek',
        pass: isLong ? ema11_1h > ema25_1h : ema11_1h < ema25_1h,
        weight: 25,
        value: `EMA11: ${ema11_1h.toFixed(5)} | EMA25: ${ema25_1h.toFixed(5)}`,
        reason: isLong
          ? ema11_1h > ema25_1h ? '1H trend is opwaarts — bevestigt LONG ✓' : '1H trend is NEERWAARTS — tegen de dagtrend'
          : ema11_1h < ema25_1h ? '1H trend is neerwaarts — bevestigt SHORT ✓' : '1H trend is OPWAARTS — tegen de dagtrend',
      },
      {
        key: 'ema_trend_4h',
        label: 'Trend 4-uurs grafiek',
        pass: isLong ? ema11_4h > ema25_4h : ema11_4h < ema25_4h,
        weight: 25,
        value: `EMA11: ${ema11_4h.toFixed(5)} | EMA25: ${ema25_4h.toFixed(5)}`,
        reason: isLong
          ? ema11_4h > ema25_4h ? '4H trend bevestigt richting ✓' : '4H trend CONFLICTEERT — sterke tegenwind'
          : ema11_4h < ema25_4h ? '4H trend bevestigt richting ✓' : '4H trend CONFLICTEERT — sterke tegenwind',
      },
      {
        key: 'ema_trend_5m',
        label: 'Korte trend (5min)',
        pass: isLong ? ema11_5m > ema25_5m : ema11_5m < ema25_5m,
        weight: 15,
        value: `EMA11: ${ema11_5m.toFixed(5)} | EMA25: ${ema25_5m.toFixed(5)}`,
        reason: isLong
          ? ema11_5m > ema25_5m ? 'Korte trend mee ✓' : 'Korte trend tegen — maar 1H/4H bepalen de richting'
          : ema11_5m < ema25_5m ? 'Korte trend mee ✓' : 'Korte trend tegen',
      },
      {
        key: 'donchian_position',
        label: 'Donchian positie',
        pass: isLong ? positionInChannel <= 40 : positionInChannel >= 60,
        weight: 20,
        value: `Positie: ${positionInChannel.toFixed(0)}% | Kanaal: ${channelWidthPips.toFixed(1)} pips`,
        reason: isLong
          ? positionInChannel <= 40
            ? `Prijs in onderste ${positionInChannel.toFixed(0)}% — gunstige entry ✓`
            : `Prijs te hoog in kanaal (${positionInChannel.toFixed(0)}%)`
          : positionInChannel >= 60
            ? `Prijs in bovenste deel — gunstige entry ✓`
            : `Prijs te laag in kanaal (${positionInChannel.toFixed(0)}%)`,
      },
      {
        key: 'mean_reversion',
        label: 'Mean reversion check',
        pass: emaDiffPips < 15,
        weight: 8,
        value: `EMA spread: ${emaDiffPips.toFixed(1)} pips`,
        reason: emaDiffPips < 15
          ? `Spread ${emaDiffPips.toFixed(1)} pips — markt niet overstretched ✓`
          : `Spread ${emaDiffPips.toFixed(1)} pips — overstretched, correctie risico`,
      },
      {
        key: 'fomo_check',
        label: 'FOMO check',
        pass: recentMovePips <= fomoThreshold,
        weight: 7,
        value: `Laatste candle: ${recentMovePips.toFixed(1)} pips`,
        reason: recentMovePips <= fomoThreshold
          ? `${recentMovePips.toFixed(1)} pips — geen FOMO ✓`
          : `${recentMovePips.toFixed(1)} pips bewogen — wacht op pull-back`,
      },
    ]

    // Apply user-customized weights & enabled/disabled state
    type UserCriterion = { key: string; label?: string; weight: number; enabled: boolean; autoGenerated?: boolean; patternKeys?: string[] }
    const criteriaMap = new Map<string, UserCriterion>(
      (userCriteria as UserCriterion[]).map((c) => [c.key, c])
    )

    // Merge default + any auto-generated user criteria
    const allCriteriaKeys = new Set([
      ...defaultCriteria.map(c => c.key),
      ...(userCriteria as UserCriterion[]).filter(c => c.autoGenerated).map((c) => c.key),
    ])

    const finalCriteria: CriterionResult[] = []

    for (const key of allCriteriaKeys) {
      const custom = criteriaMap.get(key)
      const base = defaultCriteria.find(c => c.key === key)

      if (custom?.autoGenerated && custom.patternKeys) {
        // Auto-generated pattern criterion: passes when ALL pattern criteria pass
        const patternPass = custom.patternKeys.every(pk => {
          const baseCrit = defaultCriteria.find(c => c.key === pk)
          return baseCrit?.pass ?? false
        })
        finalCriteria.push({
          key,
          label: custom.label ?? key,
          pass: patternPass,
          weight: custom.weight ?? 10,
          value: `Patroon: ${custom.patternKeys.join(' + ')}`,
          reason: patternPass ? 'Geleerd patroon aanwezig ✓' : 'Geleerd patroon niet compleet',
          autoGenerated: true,
        })
        continue
      }

      if (!base) continue

      finalCriteria.push({
        ...base,
        weight: custom?.weight ?? base.weight,
        pass: custom?.enabled === false ? false : base.pass,
        reason: custom?.enabled === false ? '(uitgeschakeld)' : base.reason,
      })
    }

    // Weighted score
    const totalWeight = finalCriteria.reduce((s, c) => s + c.weight, 0)
    const earnedWeight = finalCriteria.filter(c => c.pass).reduce((s, c) => s + c.weight, 0)
    const score = totalWeight > 0 ? Math.round((earnedWeight / totalWeight) * 100) : 0

    let recommendation: AnalysisResult['recommendation']
    if (score >= threshold) recommendation = 'WEL_DOEN'
    else if (score >= threshold - 15) recommendation = 'TWIJFEL'
    else recommendation = 'NIET_DOEN'

    const snapshot: Record<string, number | boolean> = {
      ema11_5m, ema25_5m,
      ema11_1h, ema25_1h,
      ema11_4h, ema25_4h,
      donchian_upper: donchian.upper,
      donchian_lower: donchian.lower,
      donchian_position: positionInChannel,
      ema_diff_pips: emaDiffPips,
      recent_move_pips: recentMovePips,
      score,
      ...Object.fromEntries(finalCriteria.map(c => [`criteria_${c.key}`, c.pass])),
    }

    // Sort: red first (to show problems prominently), then green
    finalCriteria.sort((a, b) => {
      if (a.pass === b.pass) return b.weight - a.weight
      return a.pass ? 1 : -1
    })

    return NextResponse.json({ score, recommendation, criteria: finalCriteria, snapshot })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Analyse mislukt'
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
